[ths_board]
host = 117.50.195.94
user = root
port = 3822
auth = key
key = /Users/cmy/Downloads/chenmingyang2@myhexin.com_rsa.key
remote_path = /mnt/aigc_team/team_workspace/ai_data_board
eval_path_port = 8000
env_file = .env